export const ADD_INGREDIENT_DETAILS: 'ADD_INGREDIENT_DETAILS' =
  'ADD_INGREDIENT_DETAILS';
export const CLEAR_INGREDIENT_DETAILS: 'CLEAR_INGREDIENT_DETAILS' =
  'CLEAR_INGREDIENT_DETAILS';

export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' =
  'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' =
  'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' =
  'GET_INGREDIENTS_FAILED';
export const ADD_INGREDIENTS: 'ADD_INGREDIENTS' = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS: 'REMOVE_INGREDIENTS' = 'REMOVE_INGREDIENTS';
export const CLEAR_INGREDIENTS: 'CLEAR_INGREDIENTS' = 'CLEAR_INGREDIENTS';
export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN';
