export const ADD_INGREDIENT_DETAILS: 'ADD_INGREDIENT_DETAILS' =
  'ADD_INGREDIENT_DETAILS';
export const CLEAR_INGREDIENT_DETAILS: 'CLEAR_INGREDIENT_DETAILS' =
  'CLEAR_INGREDIENT_DETAILS';

export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' =
  'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' =
  'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' =
  'GET_INGREDIENTS_FAILED';
export const ADD_INGREDIENTS: 'ADD_INGREDIENTS' = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS: 'REMOVE_INGREDIENTS' = 'REMOVE_INGREDIENTS';
export const CLEAR_INGREDIENTS: 'CLEAR_INGREDIENTS' = 'CLEAR_INGREDIENTS';
export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN';

export const USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS' = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST' = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_FAILED: 'USER_LOGIN_FAILED' = 'USER_LOGIN_FAILED';

export const USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST' =
  'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS' =
  'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILED: 'USER_REGISTER_FAILED' =
  'USER_REGISTER_FAILED';

export const USER_DATA_REQUEST: 'USER_DATA_REQUEST' = 'USER_DATA_REQUEST';
export const USER_DATA_SUCCESS: 'USER_DATA_SUCCESS' = 'USER_DATA_SUCCESS';
export const USER_DATA_FAILED: 'USER_DATA_FAILED' = 'USER_DATA_FAILED';

export const USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST' = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS' = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILED: 'USER_LOGOUT_FAILED' = 'USER_LOGOUT_FAILED';

export const CLEAR_USER_ERROR: 'CLEAR_USER_ERROR' = 'CLEAR_USER_ERROR';

export const ORDER_CHECKOUT_REQUEST: 'ORDER_CHECKOUT_REQUEST' =
  'ORDER_CHECKOUT_REQUEST';
export const ORDER_CHECKOUT_SUCCESS: 'ORDER_CHECKOUT_SUCCESS' =
  'ORDER_CHECKOUT_SUCCESS';
export const ORDER_CHECKOUT_FAILED: 'ORDER_CHECKOUT_FAILED' =
  'ORDER_CHECKOUT_FAILED';
